'use strict';
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
const uuid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const canvas=(w=400,h=w)=>Object.assign(document.createElement('canvas'),{width:w,height:h});
const STORAGE_KEY='docito_upload_library_v5';
const BUILTIN_IDS=new Set(['base','iron','hammer']);
let sample=null,cup=null,white=null,brandLogo=null,initialized=false,cloud=false,loadToken='',selected=new Set(),undo=[],redo=[],distribution=[];
let model=null,imageCache=new Map(),importImage=null,originalPhoto=null,rect=null,drag=null,moveGesture=null,currentPane='box',pendingFiles=[],trayGesture=null,suppressTrayClick=false,previewPrepared=false,libraryFilter='all';
let librarySerial=0,brushSerial=0,initPromise=null,sampleModels=[],legacyStamps={};
let state={schema:1,id:uuid(),client:'',theme:'',budget:null,cols:10,rows:5,quantity:50,extra:'',cells:Array(50).fill(null),library:[]};
const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
function notify(s){$('notice').textContent=s;}
function bridge(type,data={}){window.parent.postMessage({isStreamlitMessage:true,type,...data},'*');}
let resizeFrame=null,lastFrameHeight=null;
function resize(){
  if(resizeFrame!==null)return;
  resizeFrame=requestAnimationFrame(()=>{
    resizeFrame=null;
    // O retângulo do body já inclui o padding. Somar margem aqui, junto
    // com min-height:100vh, fazia o iframe crescer a cada evento resize.
    const height=Math.max(600,Math.ceil(document.body.getBoundingClientRect().height));
    if(height===lastFrameHeight)return;
    lastFrameHeight=height;
    bridge('streamlit:setFrameHeight',{height});
  });
}
function loadImage(url){if(imageCache.has(url))return imageCache.get(url);const p=new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Não foi possível carregar a imagem.'));im.src=url;});imageCache.set(url,p);return p;}
function cleanAsset(a){return a&&typeof a.id==='string'&&typeof a.name==='string'&&['Carimbado','Ejetor','Com aplique','Tradicional'].includes(a.kind)&&(!a.image||/^data:image\/(png|jpeg|webp);base64,/.test(a.image));}
function validate(s){if(s.schema!==1||![[7,7],[10,5],[10,10]].some(([c,r])=>s.cols===c&&s.rows===r)||!Array.isArray(s.cells)||s.cells.length!==s.cols*s.rows||!Array.isArray(s.library)||s.library.length>300||!s.library.every(cleanAsset)||!s.cells.every(c=>c===null||cleanAsset(c)))throw Error('Arquivo de projeto inválido.');if(!Number.isInteger(s.quantity)||s.quantity<1||s.quantity>1000)throw Error('Quantidade inválida.');return s;}
function dataDownload(content,name,type){const blob=content instanceof Blob?content:new Blob([content],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function fileStem(){return 'Docito-'+(state.client||'projeto').replace(/[^\p{L}\p{N}_-]/gu,'_');}
function checkpoint(){undo.push(JSON.stringify(state));if(undo.length>25)undo.shift();redo=[];}
function transact(fn,{persist=false}={}){checkpoint();fn();if(persist)persistLibrary();render();}
function slice(x,y,w,h){const c=canvas(w,h);c.getContext('2d').drawImage(sample,x,y,w,h,0,0,w,h);return c;}
async function prepareSample(url){if(!url){sample=cup=white=null;return;}sample=await loadImage(url);cup=slice(78,72,440,420);white=slice(126,116,341,341);const c=white.getContext('2d');c.globalCompositeOperation='destination-in';c.beginPath();c.ellipse(170,170,166,166,0,0,Math.PI*2);c.fill();c.globalCompositeOperation='source-over';}
function trimTransparent(source){const ctx=source.getContext('2d'),b=DocitoImages.bounds(ctx.getImageData(0,0,source.width,source.height).data,source.width,source.height);if(!b)return source;const pad=Math.max(3,Math.ceil(Math.max(b.width,b.height)*.025)),out=canvas(b.width+pad*2,b.height+pad*2);out.getContext('2d').drawImage(source,b.x,b.y,b.width,b.height,pad,pad,b.width,b.height);return out;}
function extractGold(source,legacy=false){const c=canvas(source.width,source.height),ctx=c.getContext('2d');ctx.drawImage(source,0,0);const im=ctx.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const [r,g,b]=[d[i],d[i+1],d[i+2]],keep=legacy?(r>110&&g>65&&r>b*1.25&&g>b*1.15&&r>g*.9):(r>100&&g>60&&r-b>30&&g-b>18&&r<g*2.3);if(!keep)d[i+3]=0;}if(!legacy)DocitoImages.cleanMask(d,c.width,c.height,2,8);ctx.putImageData(im,0,0);return (legacy?c:trimTransparent(c)).toDataURL();}

function fileBaseName(name){return String(name||'').replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').trim()||'Arte';}
async function fileToCanvas(file){if(file.size>12_000_000)throw Error('Envie imagens de até 12 MB cada.');const url=URL.createObjectURL(file),im=await loadImage(url);URL.revokeObjectURL(url);const factor=Math.min(1,1000/Math.max(im.width,im.height)),c=canvas(Math.max(1,Math.round(im.width*factor)),Math.max(1,Math.round(im.height*factor)));c.getContext('2d').drawImage(im,0,0,c.width,c.height);return c;}
function prepare2D(source,style='soft',maxColors=4){const base=trimTransparent(source),c=canvas(base.width,base.height),ctx=c.getContext('2d');ctx.drawImage(base,0,0);const im=ctx.getImageData(0,0,c.width,c.height),d=im.data;DocitoImages.simplifyEditable(d,c.width,c.height,maxColors);for(let i=0;i<d.length;i+=4){if(d[i+3]<24){d[i+3]=0;continue;}d[i+3]=255;if(style==='strong'){const lum=.299*d[i]+.587*d[i+1]+.114*d[i+2];if(lum<105){d[i]=Math.max(0,d[i]-55);d[i+1]=Math.max(0,d[i+1]-55);d[i+2]=Math.max(0,d[i+2]-55);}else{d[i]=Math.min(255,d[i]+8);d[i+1]=Math.min(255,d[i+1]+8);d[i+2]=Math.min(255,d[i+2]+8);}}}
if(style==='strong'){const copy=new Uint8ClampedArray(d);for(let y=1;y<c.height-1;y++)for(let x=1;x<c.width-1;x++){const i=(y*c.width+x)*4;if(copy[i+3]===0)continue;let edge=false;for(const n of [i-4,i+4,i-c.width*4,i+c.width*4]){if(copy[n+3]===0||Math.abs(copy[i]-copy[n])+Math.abs(copy[i+1]-copy[n+1])+Math.abs(copy[i+2]-copy[n+2])>72){edge=true;break;}}if(edge){d[i]=Math.max(0,d[i]-45);d[i+1]=Math.max(0,d[i+1]-45);d[i+2]=Math.max(0,d[i+2]-45);}}}
ctx.putImageData(im,0,0);return trimTransparent(c);}
function makeAsset({name,image,tags='',isEjetor=false}){return {id:uuid(),name,kind:isEjetor?'Ejetor':'Carimbado',tags,image,decoration:!isEjetor,mask:false,scale:isEjetor?82:72,defaultScale:isEjetor?82:72,rotation:0,assetOnly:!isEjetor};}
function isEjetorAsset(a){return !!(a&&(a.kind==='Ejetor'||a.decoration===false));}
function duplicateAssetVariant(a){const src=upgradeAsset(a);const makeEjetor=!isEjetorAsset(src);const copy=clone(src);copy.id=uuid();copy.assetId=copy.id;copy.name=src.name.replace(/ \((Arte|Ejetor)\)$/,'')+(makeEjetor?' (Ejetor)':' (Arte)');copy.kind=makeEjetor?'Ejetor':'Carimbado';copy.decoration=!makeEjetor;copy.assetOnly=!makeEjetor;copy.scale=makeEjetor?82:72;copy.defaultScale=makeEjetor?82:72;copy.rotation=0;copy.offsetX=0;copy.offsetY=0;copy.flip=false;delete copy.locked;delete copy.base;return copy;}
function trayIndexFromEvent(e){const r=$('tray').getBoundingClientRect(),col=Math.floor((e.clientX-r.left)/r.width*state.cols),row=Math.floor((e.clientY-r.top)/r.height*state.rows);return col<0||col>=state.cols||row<0||row>=state.rows?-1:row*state.cols+col;}

const BRAND={peach:'#fdbe8f',peachSoft:'#fff0e5',cream:'#fffaf7',brown:'#41261e',orange:'#f0643f',muted:'#80675d',line:'#efd4c2'};
function fitText(ctx,text,maxWidth,startSize,minSize=18,weight='700',family="system-ui, sans-serif"){let size=startSize;for(;size>minSize;size--){ctx.font=`${weight} ${size}px ${family}`;if(ctx.measureText(text).width<=maxWidth)break;}return size;}
function roundBox(ctx,x,y,w,h,r,fill,stroke=null,lineWidth=1){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lineWidth;ctx.stroke();}}
function drawCentered(ctx,text,x,y,w,font,fill){ctx.font=font;ctx.fillStyle=fill;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x+w/2,y);ctx.textAlign='left';ctx.textBaseline='alphabetic';}
function wrapLines(ctx,text,maxWidth){const words=String(text||'').trim().split(/\s+/).filter(Boolean);if(!words.length)return [''];const lines=[];let line=words[0];for(let i=1;i<words.length;i++){const test=line+' '+words[i];if(ctx.measureText(test).width<=maxWidth)line=test;else{lines.push(line);line=words[i];}}lines.push(line);return lines;}
function fitWrappedText(ctx,text,maxWidth,startSize,minSize=18,maxLines=2,weight='700',family="system-ui, sans-serif"){for(let size=startSize;size>=minSize;size--){ctx.font=`${weight} ${size}px ${family}`;const lines=wrapLines(ctx,text,maxWidth);if(lines.length<=maxLines)return {size,lines};}ctx.font=`${weight} ${minSize}px ${family}`;const lines=wrapLines(ctx,text,maxWidth);return {size:minSize,lines:lines.slice(0,maxLines)};}
function drawWrappedCentered(ctx,text,cx,cy,maxWidth,startSize,minSize,maxLines,lineHeight=1.15,weight='800',family="system-ui, sans-serif",fill=BRAND.brown){const fit=fitWrappedText(ctx,text,maxWidth,startSize,minSize,maxLines,weight,family),step=fit.size*lineHeight,startY=cy-((fit.lines.length-1)*step)/2;ctx.save();ctx.font=`${weight} ${fit.size}px ${family}`;ctx.fillStyle=fill;ctx.textAlign='center';ctx.textBaseline='middle';fit.lines.forEach((line,i)=>ctx.fillText(line,cx,startY+i*step,maxWidth));ctx.restore();return fit;}
function drawSoftLine(ctx,x1,y1,x2,y2,color='#d9ab92',lw=2){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=lw;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.restore();}
function drawHeartAccent(ctx,x,y,size=8,color=BRAND.orange){ctx.save();ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y+size*.35);ctx.bezierCurveTo(x-size*.95,y-size*.25,x-size*1.2,y-size*1.3,x,y-size*.35);ctx.bezierCurveTo(x+size*1.2,y-size*1.3,x+size*.95,y-size*.25,x,y+size*.35);ctx.fill();ctx.restore();}
async function buildProjectPresentation(){
  return DocitoPresentation.render(state,tile);
}
function dataUrlBytes(dataUrl){const bin=atob(dataUrl.split(',')[1]),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out;}
function concatBytes(parts){let total=0;for(const p of parts)total+=p.length;const out=new Uint8Array(total);let off=0;for(const p of parts){out.set(p,off);off+=p.length;}return out;}
function asciiBytes(s){return new TextEncoder().encode(s);}
function pdfFromJpeg(jpegBytes,width,height){
  const pageW=595.28,pageH=841.89,objs=[];
  objs[1]=asciiBytes('<< /Type /Catalog /Pages 2 0 R >>');
  objs[2]=asciiBytes('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');
  objs[3]=asciiBytes('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>');
  objs[4]=concatBytes([asciiBytes(`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpegBytes.length} >>\nstream\n`),jpegBytes,asciiBytes('\nendstream')]);
  const content=asciiBytes(`q\n${pageW} 0 0 ${pageH} 0 0 cm\n/Im0 Do\nQ\n`);
  objs[5]=concatBytes([asciiBytes(`<< /Length ${content.length} >>\nstream\n`),content,asciiBytes('endstream')]);
  const parts=[asciiBytes('%PDF-1.4\n%Docito\n')],offsets=[0];let cursor=parts[0].length;
  for(let i=1;i<=5;i++){offsets[i]=cursor;const head=asciiBytes(`${i} 0 obj\n`),tail=asciiBytes('\nendobj\n');parts.push(head,objs[i],tail);cursor+=head.length+objs[i].length+tail.length;}
  const xrefOffset=cursor;let xref='xref\n0 6\n0000000000 65535 f \n';for(let i=1;i<=5;i++)xref+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';xref+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  parts.push(asciiBytes(xref));return concatBytes(parts);
}
async function exportProjectPdf(){const c=await buildProjectPresentation(),jpeg=dataUrlBytes(c.toDataURL('image/jpeg',.99)),pdf=pdfFromJpeg(jpeg,c.width,c.height);dataDownload(pdf,fileStem()+'.pdf','application/pdf');}
function defaultModels(){if(!sample)return [{id:'base',name:'Branquinho',kind:'Tradicional',tags:'base branco branquinho',base:'#fff7e6',builtin:true,scale:72,rotation:0}];return [
  {id:'base',name:'Branquinho',kind:'Tradicional',tags:'base branco branquinho',base:'#fff7e6',builtin:true,scale:72,rotation:0},
  {id:'iron',name:'Homem de Ferro — exemplo',kind:'Carimbado',tags:'herói carimbo exemplo',image:extractGold(slice(685,145,245,280)),decoration:true,mask:false,builtin:true,scale:72,rotation:0},
  {id:'hammer',name:'Martelo — exemplo',kind:'Carimbado',tags:'thor carimbo exemplo',image:extractGold(slice(1175,150,225,305)),decoration:true,mask:false,builtin:true,scale:72,rotation:0}
];}
function loadLocalLibrary(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(d)?d.filter(cleanAsset):[];}catch{return [];}}
function persistLibrary(){try{const uploads=state.library.filter(a=>!BUILTIN_IDS.has(a.id));localStorage.setItem(STORAGE_KEY,JSON.stringify(uploads));}catch(e){notify('A biblioteca continua no projeto, mas o navegador não conseguiu guardar mais uploads localmente. Baixe a biblioteca como cópia.');}}
function mergeLibrary(...groups){return [...new Map(groups.flat().filter(cleanAsset).map(a=>[a.id,a])).values()];}
function upgradeAsset(asset){if(!asset)return asset;const a=clone(asset);a.offsetX=clamp(a.offsetX,-42,42);a.offsetY=clamp(a.offsetY,-42,42);if(a.id==='base'){a.name='Branquinho';a.kind='Tradicional';a.builtin=true;}if(a.kind==='Ejetor')a.decoration=false;else if(a.image&&a.decoration===undefined)a.decoration=true;if(['iron','hammer'].includes(a.id)&&a.mask&&a.image===legacyStamps[a.id]){a.image=sampleModels.find(m=>m.id===a.id).image;a.mask=false;}return a;}
function upgradeProject(s){s.cells=s.cells.map(upgradeAsset);s.library=mergeLibrary(sampleModels,s.library.map(upgradeAsset),loadLocalLibrary().map(upgradeAsset));return s;}
function blankSweet(base=model?.base||$('baseColor')?.value||'#fff7e6'){return {id:'base',name:'Branquinho',kind:'Tradicional',tags:'base branquinho',base,scale:72,rotation:0,offsetX:0,offsetY:0};}
function composeArt(asset){if(!asset?.image)return blankSweet();const isEjetor=asset.kind==='Ejetor'||asset.decoration===false;const base=model?.base||$('baseColor').value||'#fff7e6';return {id:asset.id,assetId:asset.id,name:asset.name,kind:isEjetor?'Ejetor':(asset.kind||'Carimbado'),tags:asset.tags||'',base,image:asset.image,decoration:!isEjetor,mask:!!asset.mask,ink:asset.ink||'#c99a32',scale:asset.defaultScale||asset.scale||(isEjetor?82:72),rotation:0,offsetX:0,offsetY:0,flip:false,assetOnly:!isEjetor};}
function drawBase(ctx,color){
  // Base vetorial uniforme: não herda sombras da fotografia de referência.
  // Mantém centro e diâmetro, inclusive nas montagens já salvas.
  ctx.save();ctx.shadowColor='transparent';ctx.shadowBlur=0;
  ctx.fillStyle=color||'#fff7e6';ctx.beginPath();ctx.arc(50,50,38,0,Math.PI*2);ctx.fill();ctx.restore();
}
async function drawSweet(ctx,a){if(!a)return;if(a.photoCrop){const c=slice(...a.photoCrop);ctx.save();ctx.beginPath();ctx.ellipse(50,50,40,40,0,0,Math.PI*2);ctx.clip();ctx.drawImage(c,10,10,80,80);ctx.restore();return;}if(!a.image||a.decoration)drawBase(ctx,a.base);ctx.save();ctx.translate(50+clamp(a.offsetX,-42,42),50+clamp(a.offsetY,-42,42));ctx.rotate((a.rotation||0)*Math.PI/180);if(a.flip)ctx.scale(-1,1);if(a.image){let im=await loadImage(a.image);if(a.mask){const t=canvas(im.width,im.height),tc=t.getContext('2d');tc.drawImage(im,0,0);tc.globalCompositeOperation='source-in';tc.fillStyle=a.ink||'#c99a32';tc.fillRect(0,0,t.width,t.height);im=t;}const size=(a.scale||72)*(a.decoration ? .72 : 1),ratio=im.width/im.height;ctx.drawImage(im,-size*Math.min(1,ratio)/2,-size*Math.min(1,1/ratio)/2,size*Math.min(1,ratio),size*Math.min(1,1/ratio));}if(a.text){ctx.fillStyle=a.ink||'#c99a32';ctx.font='bold '+Math.min(38,58/Math.max(1,a.text.length*.6))+'px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(a.text,0,1,68);}ctx.restore();}
async function tile(a,size=180){const c=canvas(size),ctx=c.getContext('2d');ctx.scale(size/100,size/100);ctx.fillStyle='white';ctx.fillRect(0,0,100,100);if(cup){ctx.drawImage(cup,0,0,100,100);ctx.fillStyle='#f9f9f6';ctx.beginPath();ctx.roundRect(8,8,84,84,12);ctx.fill();}await drawSweet(ctx,a);return c;}
let renderSerial=0;
async function render(){const serial=++renderSerial;syncFields();const c=$('tray'),unit=140;c.width=state.cols*unit;c.height=state.rows*unit;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);const tiles=await Promise.all(state.cells.map(a=>tile(a,unit)));if(serial!==renderSerial)return;tiles.forEach((t,i)=>{const x=i%state.cols*unit,y=Math.floor(i/state.cols)*unit;ctx.drawImage(t,x,y);if(selected.has(i)){ctx.strokeStyle='#f0643f';ctx.lineWidth=5;ctx.strokeRect(x+3,y+3,unit-6,unit-6);}if(state.cells[i]?.locked){ctx.fillStyle='#422735';ctx.fillRect(x+9,y+9,12,12);}});renderStats();$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;resize();}
function syncFields(){for(const [id,key]of [['client','client'],['theme','theme'],['quantity','quantity'],['extra','extra']])if(document.activeElement!==$(id))$(id).value=state[key]||'';$('format').value=state.cols+','+state.rows;$('position').max=state.cells.length;if($('zoomTray').getAttribute('aria-pressed')==='true')$('tray').style.minWidth=state.cols*56+'px';}
function summary(){const lines=['DOCITO · MAPA DE PRODUÇÃO','Cliente: '+state.client,'Tema: '+state.theme,'Orçamento: '+(state.budget||'não vinculado'),'Caixa: '+state.cols+' × '+state.rows,'Pedido: '+state.quantity+' doces',''],counts=new Map();for(const a of state.cells){if(!a)continue;const key=(a.name||'Branquinho')+' · cor '+(a.base||'original');counts.set(key,(counts.get(key)||0)+1);}for(const [k,v]of counts)lines.push(v+' × '+k);const n=state.cells.filter(Boolean).length;lines.push('','Na caixa: '+n,'Ainda fora da montagem: '+Math.max(0,state.quantity-n),'Separados: '+(state.extra||'não informado'));return lines.join('\n');}
function renderStats(){const n=state.cells.filter(Boolean).length,diff=state.quantity-n;$('stats').textContent=n+' / '+state.cells.length+' posições preenchidas · '+(diff>=0?diff+' doces do pedido ainda fora da montagem':(-diff)+' doces além do pedido');$('summary').textContent=summary();}
async function library(){const serial=++librarySerial,q=norm($('search').value),unique=[...new Map(state.library.map(a=>[a.id,a])).values()];const items=unique.filter(a=>{if(BUILTIN_IDS.has(a.id)||!a.image)return false;const isEjetor=isEjetorAsset(a);if(libraryFilter==='art'&&isEjetor)return false;if(libraryFilter==='ejetor'&&!isEjetor)return false;return !q||norm(a.name+' '+(a.tags||'')).includes(q);});const cards=await Promise.all(items.map(async a=>{const b=document.createElement('button');b.className='card'+((model?.assetId||model?.id)===a.id?' active':'');const overlay=a.decoration!==false||a.assetOnly,preview=overlay?composeArt(a):upgradeAsset(a),im=document.createElement('img');im.alt=a.name;im.src=(await tile(preview,140)).toDataURL();const name=document.createElement('span');name.textContent=a.name;const meta=document.createElement('small');meta.className='muted';meta.textContent=isEjetorAsset(a)?'Ejetor':'Arte';b.append(im,name,meta);b.onclick=()=>{model=overlay?composeArt(a):upgradeAsset(a);syncModelFields();renderBrush();library();showPane('settings');notify(isEjetorAsset(a)?'Ejetor escolhido. Ele será usado sem base de doce.':'Arte escolhida. Arraste-a sobre o brigadeiro e depois aplique na caixa.');};return b;}));if(serial!==librarySerial)return;$('catalog').replaceChildren(...cards);resize();}
function setLibraryFilter(filter='all'){libraryFilter=filter;for(const b of document.querySelectorAll('[data-filter]'))b.setAttribute('aria-pressed',String(b.dataset.filter===filter));library();}
function syncModelFields(){if(!model)model=blankSweet();const isEjetor=!!(model.image&&model.decoration===false);$('modelName').textContent=model.image?(isEjetor?'Ejetor: ':'Arte: ')+model.name:'Branquinho sem arte';$('baseColor').value=model.base||'#fff7e6';$('scale').value=model.scale??72;$('rotation').value=model.rotation??0;$('offsetX').value=model.offsetX??0;$('offsetY').value=model.offsetY??0;const canAdjustImage=!!model.image;const canMoveOverlay=!!(model.image&&model.decoration);$('baseColor').disabled=isEjetor;for(const id of ['scale','rotation','offsetX','offsetY'])$(id).disabled=!canAdjustImage;for(const id of ['flip','centerDecoration'])$(id).disabled=!canMoveOverlay;}
async function renderBrush(){const serial=++brushSerial,a=clone(model||blankSweet()),preview=await tile(a,400);if(serial!==brushSerial)return;const ctx=$('paint').getContext('2d');ctx.clearRect(0,0,400,400);ctx.drawImage(preview,0,0);$('paint').classList.toggle('drag-disabled',!a.image||!a.decoration);$('paintHint').textContent=a.image?(a.decoration?'Arraste a arte para qualquer ponto do brigadeiro. Use os controles para tamanho e rotação.':'Ejetor selecionado: este upload fica sem base de doce e entra como o próprio doce.'): 'Escolha uma arte na biblioteca para colocar sobre o branquinho.';}
function updateModel(){if(!model)model=blankSweet();model.base=$('baseColor').value;model.scale=+$('scale').value;model.rotation=+$('rotation').value;model.offsetX=clamp($('offsetX').value,-42,42);model.offsetY=clamp($('offsetY').value,-42,42);renderBrush();}
function showPane(pane){currentPane=pane;for(const [p,id]of [['box','boxPanel'],['library','libraryPanel'],['settings','settingsPanel']])$(id).classList.toggle('active-pane',p===pane);for(const b of document.querySelectorAll('[data-pane]'))b.setAttribute('aria-pressed',String(b.dataset.pane===pane));resize();}
for(const b of document.querySelectorAll('[data-pane]'))b.onclick=()=>showPane(b.dataset.pane);
$('mode').onchange=()=>{$('tray').style.touchAction=$('mode').value==='drag'?'none':'pan-x pan-y';notify($('mode').value==='drag'?'Modo arrastar ativo: segure um doce e mova para outra posição.':'Modo de montagem alterado.');};
$('plainBase').onclick=$('noArt').onclick=()=>{const base=model?.base||$('baseColor').value;model=blankSweet(base);syncModelFields();renderBrush();library();showPane('settings');notify('Branquinho selecionado. Escolha a cor ou aplique sem arte.');};
$('baseColor').oninput=updateModel;for(const b of document.querySelectorAll('[data-color]')){b.style.background=b.dataset.color;b.onclick=()=>{$('baseColor').value=b.dataset.color;updateModel();};}
for(const id of ['scale','rotation','offsetX','offsetY'])$(id).oninput=updateModel;
$('flip').onclick=()=>{if(model?.image&&model.decoration){model.flip=!model.flip;renderBrush();}};
$('centerDecoration').onclick=()=>{if(!model)return;model.offsetX=0;model.offsetY=0;syncModelFields();renderBrush();};
$('search').oninput=library;for(const b of document.querySelectorAll('[data-filter]'))b.onclick=()=>setLibraryFilter(b.dataset.filter);
$('fitTray').onclick=()=>{$('tray').style.minWidth='0';$('fitTray').setAttribute('aria-pressed','true');$('zoomTray').setAttribute('aria-pressed','false');resize();};
$('zoomTray').onclick=()=>{$('tray').style.minWidth=state.cols*56+'px';$('fitTray').setAttribute('aria-pressed','false');$('zoomTray').setAttribute('aria-pressed','true');resize();};
function apply(indices){if(!model)return;transact(()=>{for(const i of indices)if(i>=0&&i<state.cells.length&&!state.cells[i]?.locked){state.cells[i]=clone(model);delete state.cells[i].locked;}});}
function activePos(){return Math.max(0,Math.min(state.cells.length-1,Number($('position').value)-1));}
$('tray').onclick=e=>{if(suppressTrayClick){suppressTrayClick=false;return;}const i=trayIndexFromEvent(e);if(i<0||i>=state.cells.length)return;$('position').value=i+1;const mode=$('mode').value;if(mode==='drag')return;if(mode==='place')apply([i]);else if(mode==='select'){selected.has(i)?selected.delete(i):selected.add(i);render();}else if(mode==='erase'){transact(()=>{if(!state.cells[i]?.locked)state.cells[i]=null;});}else if(state.cells[i])transact(()=>state.cells[i].locked=!state.cells[i].locked);};

$('tray').onpointerdown=e=>{if($('mode').value!=='drag'||e.button>0)return;const from=trayIndexFromEvent(e);if(from<0||!state.cells[from]||state.cells[from]?.locked)return;trayGesture={id:e.pointerId,from,to:from,moved:false};$('tray').setPointerCapture(e.pointerId);e.preventDefault();};
$('tray').onpointermove=e=>{if(!trayGesture||trayGesture.id!==e.pointerId)return;const to=trayIndexFromEvent(e);if(to>=0){trayGesture.to=to;trayGesture.moved=trayGesture.moved||to!==trayGesture.from;}e.preventDefault();};
$('tray').onpointerup=e=>{if(!trayGesture||trayGesture.id!==e.pointerId)return;const move=trayGesture;trayGesture=null;if($('tray').hasPointerCapture(e.pointerId))$('tray').releasePointerCapture(e.pointerId);suppressTrayClick=true;setTimeout(()=>suppressTrayClick=false,0);if(!move.moved||move.to<0||move.to===move.from){notify('Arraste o doce para outra posição da caixa.');return;}if(state.cells[move.to]?.locked){notify('A posição de destino está fixa.');return;}transact(()=>{const origin=state.cells[move.from],dest=state.cells[move.to]||null;state.cells[move.to]=origin;state.cells[move.from]=dest;selected.clear();selected.add(move.to);$('position').value=move.to+1;});notify(state.cells[move.from]?'Doces trocados de posição.':'Doce movido para a nova posição.');};
$('tray').onpointercancel=e=>{if(trayGesture?.id===e.pointerId){trayGesture=null;suppressTrayClick=true;setTimeout(()=>suppressTrayClick=false,0);}};
$('line').onclick=()=>apply(Array.from({length:state.cols},(_,i)=>Math.floor(activePos()/state.cols)*state.cols+i));
$('column').onclick=()=>apply(Array.from({length:state.rows},(_,i)=>activePos()%state.cols+i*state.cols));
$('selected').onclick=()=>selected.size?apply([...selected]):notify('Selecione posições na caixa primeiro.');$('replace').onclick=$('selected').onclick;
$('empty').onclick=()=>apply(state.cells.map((a,i)=>a?null:i).filter(i=>i!==null));$('deselect').onclick=()=>{selected.clear();render();};$('placePosition').onclick=()=>apply([activePos()]);
$('editPosition').onclick=()=>{const a=state.cells[activePos()];if(!a)return notify('Essa posição está vazia.');selected=new Set([activePos()]);model=upgradeAsset(a);syncModelFields();renderBrush();library();showPane('settings');render();};
$('format').onchange=()=>{const [c,r]=$('format').value.split(',').map(Number);if(c*r<state.cells.length&&state.cells.slice(c*r).some(Boolean)&&!confirm('A nova caixa tem menos posições. Remover as posições excedentes?')){syncFields();return;}transact(()=>{state.cols=c;state.rows=r;state.cells=Array.from({length:c*r},(_,i)=>state.cells[i]||null);selected.clear();});};
for(const [id,key]of [['client','client'],['theme','theme'],['extra','extra']])$(id).onchange=()=>transact(()=>state[key]=$(id).value);$('quantity').onchange=()=>transact(()=>state.quantity=Math.max(1,Math.min(1000,Math.trunc(+$('quantity').value)||1)));
$('undo').onclick=()=>{if(!undo.length)return;redo.push(JSON.stringify(state));state=JSON.parse(undo.pop());selected.clear();persistLibrary();library();render();};$('redo').onclick=()=>{if(!redo.length)return;undo.push(JSON.stringify(state));state=JSON.parse(redo.pop());selected.clear();persistLibrary();library();render();};
$('distAdd').onclick=()=>{if(!model)return;const qty=Math.trunc(+$('distQty').value);if(qty<1||qty>1000)return;distribution.push({model:clone(model),qty});$('distList').textContent=distribution.map(d=>d.qty+' × '+d.model.name).join(' · ');};$('distClear').onclick=()=>{distribution=[];$('distList').textContent='';};$('distribute').onclick=()=>{const slots=state.cells.map((a,i)=>a?.locked?null:i).filter(i=>i!==null),total=distribution.reduce((n,d)=>n+d.qty,0);if(!total)return;if(total>slots.length)return notify('A quantidade ultrapassa as posições disponíveis.');if(slots.some(i=>state.cells[i])&&!confirm('Substituir os doces das posições livres pela distribuição?'))return;const list=distribution.map(d=>({...d,remaining:d.qty})),out=[];while(out.length<total)for(const d of list)if(d.remaining>0){out.push(clone(d.model));d.remaining--;}transact(()=>slots.forEach((i,j)=>state.cells[i]=out[j]||null));};
$('download').onclick=()=>dataDownload(JSON.stringify(state),fileStem()+'.json','application/json');$('libraryDownload').onclick=()=>dataDownload(JSON.stringify({schema:1,library:state.library.filter(a=>!BUILTIN_IDS.has(a.id))}),'Docito-biblioteca.json','application/json');
async function readJSON(input){const f=input.files[0];if(!f)return null;if(f.size>25_000_000)throw Error('Arquivo acima de 25 MB.');return JSON.parse(await f.text());}
$('open').onchange=async()=>{try{const s=await readJSON($('open'));if(!s)return;validate(s);if(state.cells.some(Boolean)&&!confirm('Abrir o arquivo e substituir a montagem atual?'))return;checkpoint();state=upgradeProject(s);persistLibrary();selected.clear();model=blankSweet(state.cells.find(Boolean)?.base||'#fff7e6');await library();syncModelFields();renderBrush();showPane('box');render();notify('Projeto aberto. Seus uploads foram mantidos na biblioteca.');}catch(e){notify(e.message);}$('open').value='';};
$('libraryOpen').onchange=async()=>{try{const d=await readJSON($('libraryOpen'));if(!d||d.schema!==1||!Array.isArray(d.library)||d.library.length>300||!d.library.every(cleanAsset))throw Error('Biblioteca inválida.');transact(()=>{state.library=mergeLibrary(state.library,d.library.map(upgradeAsset));},{persist:true});library();notify('Biblioteca importada e guardada neste navegador.');}catch(e){notify(e.message);}$('libraryOpen').value='';};
$('report').onclick=()=>dataDownload(summary(),fileStem()+'-producao.txt','text/plain;charset=utf-8');$('save').onclick=()=>{if(!state.client.trim())return notify('Preencha o nome da cliente.');if(!cloud){$('download').click();notify('Projeto editável baixado.');return;}bridge('streamlit:setComponentValue',{value:{event_id:uuid(),project:clone(state)},dataType:'json'});notify('Versão enviada para salvamento.');};
$('png').onclick=async()=>{try{notify('Preparando apresentação Docito em alta resolução…');const c=await buildProjectPresentation();c.toBlob(b=>{dataDownload(b,fileStem()+'.png','image/png');notify('Apresentação PNG exportada no padrão Docito.');},'image/png');}catch(e){notify('Não foi possível exportar: '+e.message);}};
$('pdf').onclick=async()=>{try{notify('Preparando PDF do projeto no padrão Docito…');await exportProjectPdf();notify('PDF do projeto exportado.');}catch(e){notify('Não foi possível gerar o PDF: '+e.message);}};
function previewPoint(e){const r=$('paint').getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100};}
$('paint').onpointerdown=e=>{if(!model?.image||!model.decoration||e.button>0)return;const p=previewPoint(e);moveGesture={id:e.pointerId,x:p.x,y:p.y,ox:clamp(model.offsetX,-42,42),oy:clamp(model.offsetY,-42,42)};$('paint').setPointerCapture(e.pointerId);$('paint').classList.add('dragging');e.preventDefault();};
$('paint').onpointermove=e=>{if(!moveGesture||moveGesture.id!==e.pointerId)return;const p=previewPoint(e);model.offsetX=clamp(moveGesture.ox+p.x-moveGesture.x,-42,42);model.offsetY=clamp(moveGesture.oy+p.y-moveGesture.y,-42,42);$('offsetX').value=model.offsetX;$('offsetY').value=model.offsetY;renderBrush();e.preventDefault();};
$('paint').onpointerup=e=>{if(!moveGesture||moveGesture.id!==e.pointerId)return;moveGesture=null;$('paint').classList.remove('dragging');if($('paint').hasPointerCapture(e.pointerId))$('paint').releasePointerCapture(e.pointerId);notify('Posição da arte ajustada. Agora aplique na caixa.');};
$('paint').onpointercancel=e=>{if(moveGesture?.id===e.pointerId){model.offsetX=moveGesture.ox;model.offsetY=moveGesture.oy;moveGesture=null;syncModelFields();renderBrush();$('paint').classList.remove('dragging');}};
$('paint').onkeydown=e=>{if(!model?.image||!model.decoration)return;const step=e.shiftKey?5:1,delta={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]}[e.key];if(!delta)return;e.preventDefault();model.offsetX=clamp((model.offsetX||0)+delta[0],-42,42);model.offsetY=clamp((model.offsetY||0)+delta[1],-42,42);syncModelFields();renderBrush();};
function flood(data,w,h,x,y,tolerance){x=Math.floor(x);y=Math.floor(y);if(x<0||x>=w||y<0||y>=h)return;const i=(y*w+x)*4,target=data.slice(i,i+4);if(target[3]===0)return;const seen=new Uint8Array(w*h),queue=[y*w+x];seen[y*w+x]=1;for(let p=0;p<queue.length;p++){const pos=queue[p],j=pos*4;if(Math.max(Math.abs(data[j]-target[0]),Math.abs(data[j+1]-target[1]),Math.abs(data[j+2]-target[2]),Math.abs(data[j+3]-target[3]))>tolerance)continue;data[j+3]=0;const px=pos%w;for(const n of [px>0?pos-1:-1,px<w-1?pos+1:-1,pos-w,pos+w])if(n>=0&&n<w*h&&!seen[n]){seen[n]=1;queue.push(n);}}}
function autoRemoveEdgeBackground(source){const c=canvas(source.width,source.height),ctx=c.getContext('2d');ctx.drawImage(source,0,0);const d=ctx.getImageData(0,0,c.width,c.height);for(const [x,y]of [[0,0],[c.width-1,0],[0,c.height-1],[c.width-1,c.height-1]])flood(d.data,c.width,c.height,x,y,42);ctx.putImageData(d,0,0);return trimTransparent(c);}
function drawPhoto(){const c=$('photo'),ctx=c.getContext('2d');if(!importImage){ctx.clearRect(0,0,c.width,c.height);return;}c.width=importImage.width;c.height=importImage.height;ctx.drawImage(importImage,0,0);if(rect){ctx.strokeStyle='#f0643f';ctx.lineWidth=Math.max(2,c.width/200);ctx.strokeRect(rect.x,rect.y,rect.w,rect.h);}}
$('import').onclick=()=>{$('newName').value='';$('tags').value='';$('isEjetor').checked=false;$('prepStyle').value='none';$('prepColors').value='4';$('upload').value='';$('uploadCount').textContent='Nenhum arquivo selecionado.';pendingFiles=[];previewPrepared=false;importImage=originalPhoto=null;rect=null;drawPhoto();$('importDialog').showModal();};$('closeImport').onclick=()=>$('importDialog').close();
$('upload').onchange=async()=>{const files=[...$('upload').files||[]];pendingFiles=files;$('uploadCount').textContent=files.length?files.length+' arquivo(s) selecionado(s).':'Nenhum arquivo selecionado.';const f=files[0];if(!f){importImage=originalPhoto=null;rect=null;drawPhoto();return;}try{const c=await fileToCanvas(f);originalPhoto=c;importImage=autoRemoveEdgeBackground(c);previewPrepared=false;rect=null;if(files.length===1&&!$('newName').value.trim())$('newName').value=fileBaseName(f.name);drawPhoto();}catch(e){notify(e.message);}};
function photoPoint(e){const r=$('photo').getBoundingClientRect();return{x:Math.max(0,Math.min($('photo').width,(e.clientX-r.left)/r.width*$('photo').width)),y:Math.max(0,Math.min($('photo').height,(e.clientY-r.top)/r.height*$('photo').height))};}
$('photo').onpointerdown=e=>{drag=photoPoint(e);$('photo').setPointerCapture(e.pointerId);};$('photo').onpointermove=e=>{if(!drag)return;const p=photoPoint(e);rect={x:Math.min(drag.x,p.x),y:Math.min(drag.y,p.y),w:Math.abs(p.x-drag.x),h:Math.abs(p.y-drag.y)};drawPhoto();};$('photo').onpointerup=()=>drag=null;
$('crop').onclick=()=>{if(!importImage||!rect||rect.w<3||rect.h<3)return;const c=canvas(Math.round(rect.w),Math.round(rect.h));c.getContext('2d').drawImage(importImage,rect.x,rect.y,rect.w,rect.h,0,0,c.width,c.height);importImage=trimTransparent(c);previewPrepared=false;rect=null;drawPhoto();};$('resetPhoto').onclick=()=>{importImage=originalPhoto?autoRemoveEdgeBackground(originalPhoto):null;previewPrepared=false;rect=null;drawPhoto();};

$('prepare2d').onclick=()=>{if(!importImage)return notify('Escolha uma imagem primeiro.');const style=$('prepStyle').value;if(style==='none')return notify('Escolha 2D suave ou 2D forte para preparar a imagem.');importImage=prepare2D(importImage,style,Number($('prepColors').value)||4);previewPrepared=true;rect=null;drawPhoto();notify('Prévia preparada em 2D.');};
function canvasDataURL(c){try{return c.toDataURL('image/webp',.9);}catch{return c.toDataURL();}}
$('confirmImport').onclick=async()=>{if(!importImage&&!pendingFiles.length)return notify('Escolha pelo menos uma imagem.');const isEjetor=$('isEjetor').checked,tags=$('tags').value,style=$('prepStyle').value,colors=Number($('prepColors').value)||4;const files=pendingFiles.length?pendingFiles:[{name:$('newName').value||'Arte'}];const created=[];try{if(files.length===1){const finalCanvas=trimTransparent(style!=='none'&&!previewPrepared?prepare2D(importImage,style,colors):importImage);const image=canvasDataURL(finalCanvas);const name=$('newName').value.trim()||fileBaseName(files[0].name);created.push(makeAsset({name,image,tags,isEjetor}));}else{notify('Processando uploads em massa…');for(const f of files){let c=autoRemoveEdgeBackground(await fileToCanvas(f));if(style!=='none')c=prepare2D(c,style,colors);const image=canvasDataURL(trimTransparent(c));created.push(makeAsset({name:fileBaseName(f.name),image,tags,isEjetor}));}}transact(()=>state.library.push(...created),{persist:true});model=composeArt(created[0]);syncModelFields();renderBrush();library();$('importDialog').close();showPane('settings');notify(created.length>1?created.length+' uploads salvos na biblioteca.':'Upload salvo na biblioteca.');}catch(e){notify(e.message);}};
function selectedLibraryAsset(){const id=model?.assetId||model?.id;return state.library.find(a=>a.id===id&&a.image&&!BUILTIN_IDS.has(a.id));}
$('duplicateModel').onclick=()=>{const a=selectedLibraryAsset();if(!a)return notify('Escolha um upload seu na biblioteca para duplicar.');const copy=duplicateAssetVariant(a);transact(()=>state.library.push(copy),{persist:true});model=composeArt(copy);syncModelFields();renderBrush();library();showPane('settings');notify('Cadastro duplicado como '+(isEjetorAsset(copy)?'Ejetor':'Arte')+'.');};
$('editUpload').onclick=()=>{const a=selectedLibraryAsset();if(!a)return notify('Escolha um upload seu na biblioteca para editar.');$('editName').value=a.name;$('editTags').value=a.tags||'';$('editIsEjetor').checked=a.kind==='Ejetor'||a.decoration===false;$('editFile').value='';$('editError').textContent='';$('editUploadDialog').showModal();};$('closeEditUpload').onclick=()=>$('editUploadDialog').close();
$('commitEditUpload').onclick=async()=>{const a=selectedLibraryAsset(),name=$('editName').value.trim();if(!a||!name){$('editError').textContent='Preencha o nome.';return;}try{let image=a.image;const isEjetor=$('editIsEjetor').checked;const f=$('editFile').files[0];if(f){if(f.size>12_000_000)throw Error('Escolha uma imagem de até 12 MB.');const url=URL.createObjectURL(f),im=await loadImage(url);URL.revokeObjectURL(url);const factor=Math.min(1,1000/Math.max(im.width,im.height)),c=canvas(Math.round(im.width*factor),Math.round(im.height*factor));c.getContext('2d').drawImage(im,0,0,c.width,c.height);image=canvasDataURL(autoRemoveEdgeBackground(c));}const replacement={...a,name,kind:isEjetor?'Ejetor':'Carimbado',tags:$('editTags').value,image,decoration:!isEjetor,scale:isEjetor?82:72,defaultScale:isEjetor?82:72,assetOnly:!isEjetor};transact(()=>{const i=state.library.findIndex(x=>x.id===a.id);state.library[i]=replacement;},{persist:true});model=composeArt(replacement);syncModelFields();renderBrush();library();$('editUploadDialog').close();notify('Upload atualizado e mantido na biblioteca.');}catch(e){$('editError').textContent=e.message;}};
$('deleteModel').onclick=()=>{const a=selectedLibraryAsset();if(!a)return notify('Escolha um upload seu para excluir.');if(!confirm('Excluir “'+a.name+'” da biblioteca? Os doces já colocados na caixa continuarão como estão.'))return;transact(()=>state.library=state.library.filter(x=>x.id!==a.id),{persist:true});model=blankSweet(model?.base);syncModelFields();renderBrush();library();notify('Upload excluído da biblioteca. Os doces já montados foram preservados.');};
async function ensureInitialized(args){if(initialized)return;if(!initPromise)initPromise=(async()=>{await prepareSample(args.sample);try{brandLogo=await loadImage(args.logo||'logo-docito.png');}catch{brandLogo=null;}legacyStamps=sample?{iron:extractGold(slice(700,150,226,257),true),hammer:extractGold(slice(1180,150,210,295),true)}:{};sampleModels=defaultModels();state.library=mergeLibrary(sampleModels,loadLocalLibrary().map(upgradeAsset));state.client=args.client||'';state.budget=args.budget||null;model=blankSweet();initialized=true;syncModelFields();await Promise.all([renderBrush(),library()]);})().catch(e=>{initPromise=null;initialized=false;throw e;});await initPromise;}
window.addEventListener('message',async e=>{if(e.source!==window.parent||e.data?.type!=='streamlit:render')return;try{const args=e.data.args;cloud=!!args.cloud;await ensureInitialized(args);if(args.initial&&args.load_token!==loadToken){const next=upgradeProject(validate(clone(args.initial)));loadToken=args.load_token;state=next;persistLibrary();undo=[];redo=[];selected.clear();model=blankSweet();syncModelFields();await Promise.all([library(),renderBrush()]);showPane('box');}await render();}catch(err){notify('Falha ao abrir editor: '+err.message);}});
window.addEventListener('resize',resize);
// Também acompanha conteúdo que abre/fecha e imagens que terminam de carregar.
if(typeof ResizeObserver!=='undefined')new ResizeObserver(resize).observe(document.body);
showPane('box');bridge('streamlit:componentReady',{apiVersion:1});resize();const embedConfig=window.DOCITO_EMBED_CONFIG;if(embedConfig){ensureInitialized(embedConfig).then(render).catch(e=>notify(e.message));}else if(window.parent===window){ensureInitialized({sample:'../assets/amostra.png'}).then(render).catch(e=>notify(e.message));}
